# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a58af31289e5b70618ecaedaf46a88e2ca8cd9098bd6d1bbbb8544105eb81a9a58c3a39ffbc1fa2f77f2ab7504b1928d318580b1719e281f73b0a561ec3b43

test:
  secret_key_base: 88f0f8a67f5fddc677514d0643648898687591ef08cdce051d95e1ea05a6c0f85f94c13614cf1dea5af0e2e444f4c117168bd403a782c0b4cb4152de14a698ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
